export const CONFIG_NODE_ENV = 'NODE_ENV';
export const CONFIG_HTTP_TIMEOUT = 'HTTP_TIMEOUT';

export const CONFIG_TRANSACTION_ID_HEADER = 'x-transaction-id';

export const CONFIG_COUCHBASE_HOST = 'CONFIG_COUCHBASE_HOST';
export const CONFIG_COUCHBASE_USERNAME = 'CONFIG_COUCHBASE_USERNAME';
export const CONFIG_COUCHBASE_PASSWORD = 'CONFIG_COUCHBASE_PASSWORD';
export const CONFIG_COUCHBASE_BUCKET = 'CONFIG_COUCHBASE_BUCKET';